probes:
  cloudlfare-dns:
    http:
      method: GET
      url: https://1.1.1.1/
      interval: 60
      timeout: 10
  google:
    http:
      method: HEAD
      url: http://google.com
  railway:
    http:
      method: HEAD
      url: http://railway.com
  github:
    http:
      url: http://github.com

exporters:
  web:
    enabled: true

taskhost:
  autorun: false
