probes:
  cloudlfare-dns:
    http:
      method: GET
      url: https://1.1.1.1/
      timeout: 15s
  google:
    http:
      method: HEAD
      url: http://google.com
      interval: 10s
      timeout: 5s
  railway:
    http:
      method: HEAD
      url: http://railway.com
      timeout: 35
  github:
    http:
      url: http://github.com

exporters:
  web:
    enabled: true

taskhost:
  autorun: false
