// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"database/sql"
	"time"
)

type Tlscert struct {
	ID              int64
	Time            time.Time
	Label           string
	Security        string
	CertSubject     sql.NullString
	CertIssuer      sql.NullString
	CertExpires     sql.NullTime
	CertFingerprint sql.NullString
}

type Uptime struct {
	ID         int64
	Time       time.Time
	Label      string
	Status     string
	HttpStatus sql.NullInt16
	ElapsedMs  int64
	Latency    int32
}
