// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"database/sql"
	"time"
)

type Series struct {
	ID         int64
	Time       time.Time
	Label      string
	Status     string
	HttpStatus sql.NullInt16
	ElapsedMs  int64
	Latency    sql.NullInt64
}
