// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"database/sql"
)

type Series struct {
	ID         int64
	Time       int64
	Label      string
	Status     string
	HttpStatus sql.NullInt64
	Elapsed    int64
}
